name: dist.yml
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    workflow_dispatch:

jobs:
    build:
        name: Build and Publish Distribution Package
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '25.x'
            cache: 'npm'

        - name: Install Dependencies
          run: npm install

        - name: Build Distribution Package
          run: npm run generate

        - name: Get Version
          id: get_version
          run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

        - name: Create Distribution Archive
          run: |
            mkdir -p dist
            cd .output
            zip -r ../dist/dist-v${{ steps.get_version.outputs.version }}.zip ./public/


        - name: Create Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: dist-v${{ steps.get_version.outputs.version }}
            name: v${{ steps.get_version.outputs.version }}
            body: | 
              Automated distribution package release v${{ steps.get_version.outputs.version }}
              Commit: ${{ github.sha }} - ${{ github.event.head_commit.message }}
            files: ./dist/dist-v${{ steps.get_version.outputs.version }}.zip
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
